apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: okoobohjames/ecommerce-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/ecommerce
            - name: REACT_APP_FRONTEND_URL
              value: http://localhost:30080
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
  type: NodePort
